# Generated by Django 5.0.1 on 2026-01-07 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_record_number",
                    models.CharField(db_index=True, max_length=50),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Unknown"),
                        ],
                        max_length=1,
                    ),
                ),
                ("ssn_encrypted", models.CharField(blank=True, max_length=500)),
                ("phone_primary", models.CharField(max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(default="TX", max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "insurance_primary_company",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "insurance_primary_policy_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "insurance_primary_group_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "insurance_primary_subscriber_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "insurance_primary_subscriber_dob",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "insurance_secondary_company",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "insurance_secondary_policy_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "insurance_secondary_group_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("other", "Other"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "privacy_restrictions",
                    models.JSONField(
                        default=dict,
                        help_text="Patient-requested restrictions on PHI disclosure",
                    ),
                ),
                ("consent_for_treatment", models.BooleanField(default=False)),
                ("consent_for_phi_disclosure", models.BooleanField(default=False)),
                (
                    "notice_of_privacy_practices_provided",
                    models.BooleanField(default=False),
                ),
                (
                    "notice_of_privacy_practices_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="patient_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deceased", models.BooleanField(default=False)),
                ("deceased_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_retention_date",
                    models.DateField(
                        blank=True,
                        help_text="Date after which record can be archived/deleted",
                        null=True,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patients",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dosage", models.CharField(blank=True, max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'twice daily', 'as needed'",
                        max_length=100,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True, help_text="e.g., 'oral', 'topical'", max_length=50
                    ),
                ),
                ("prescribed_by", models.CharField(blank=True, max_length=200)),
                ("prescribed_date", models.DateField(blank=True, null=True)),
                (
                    "indication",
                    models.CharField(
                        blank=True, help_text="Why prescribed", max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("discontinued_date", models.DateField(blank=True, null=True)),
                ("discontinued_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("imported_from_imed", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "medications",
                "ordering": ["is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="FamilyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("sibling", "Sibling"),
                            ("grandparent", "Grandparent"),
                            ("child", "Child"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition", models.CharField(max_length=200)),
                ("age_at_diagnosis", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_history",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Family histories",
                "db_table": "family_history",
            },
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.CharField(
                        help_text="Drug, food, or environmental allergen",
                        max_length=200,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe/Anaphylaxis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reaction",
                    models.TextField(help_text="Description of allergic reaction"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("onset_date", models.DateField(blank=True, null=True)),
                (
                    "reported_by",
                    models.CharField(
                        blank=True, help_text="Patient, family, etc.", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("imported_from_imed", models.BooleanField(default=False)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "allergies",
                "ordering": ["-severity", "allergen"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("icd10_code", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("chronic", "Chronic"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("severity", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("imported_from_imed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "problems",
                "ordering": ["status", "-onset_date"],
            },
        ),
        migrations.CreateModel(
            name="SocialHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tobacco_use",
                    models.CharField(
                        choices=[
                            ("never", "Never used"),
                            ("former", "Former user"),
                            ("current", "Current user"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                (
                    "tobacco_packs_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("tobacco_years", models.IntegerField(blank=True, null=True)),
                ("tobacco_quit_date", models.DateField(blank=True, null=True)),
                (
                    "alcohol_use",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("occasional", "Occasional"),
                            ("moderate", "Moderate"),
                            ("heavy", "Heavy"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("alcohol_drinks_per_week", models.IntegerField(blank=True, null=True)),
                ("illicit_drug_use", models.BooleanField(default=False)),
                ("illicit_drug_details", models.TextField(blank=True)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("occupational_hazards", models.TextField(blank=True)),
                ("exercise_frequency", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_history",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social histories",
                "db_table": "social_history",
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "medical_record_number"],
                name="patients_clinic__309200_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "last_name", "first_name"],
                name="patients_clinic__320d94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "date_of_birth"], name="patients_clinic__55e0e9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together={("clinic", "medical_record_number")},
        ),
    ]
