# Generated by Django 5.0.1 on 2026-01-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ethnicity",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender_identity",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="race",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="sexual_orientation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="privacy_restrictions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Patient-requested restrictions on PHI disclosure",
            ),
        ),
    ]
