# Generated by Django 5.0.1 on 2026-01-15 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("encounters", "0001_initial"),
        ("patients", "0002_patient_ethnicity_patient_gender_identity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("oct", "OCT Scan"),
                            ("fundus_photo", "Fundus Photography"),
                            ("visual_field", "Visual Field"),
                            ("xray", "X-ray"),
                            ("mri", "MRI"),
                            ("ct", "CT Scan"),
                            ("ultrasound", "Ultrasound"),
                            ("photo_preop", "Pre-operative Photo"),
                            ("photo_postop", "Post-operative Photo"),
                            ("photo_cosmetic", "Cosmetic Photo"),
                            ("document", "Scanned Document"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("ophthalmology", "Ophthalmology"),
                            ("orthopedics", "Orthopedics"),
                            ("cosmetic", "Cosmetic Surgery"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "laterality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OD", "Right Eye (OD)"),
                            ("OS", "Left Eye (OS)"),
                            ("OU", "Both Eyes (OU)"),
                            ("right", "Right"),
                            ("left", "Left"),
                            ("bilateral", "Bilateral"),
                            ("n/a", "Not Applicable"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "body_location",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Face', 'Right Knee', 'Abdomen'",
                        max_length=100,
                    ),
                ),
                ("image_file", models.FileField(upload_to="clinical-images/%Y/%m/%d/")),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True, null=True, upload_to="thumbnails/%Y/%m/%d/"
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="Size in bytes")),
                ("mime_type", models.CharField(max_length=100)),
                ("original_filename", models.CharField(max_length=255)),
                ("is_dicom", models.BooleanField(default=False)),
                (
                    "dicom_metadata",
                    models.JSONField(
                        blank=True,
                        help_text='\n        DICOM tags:\n        {\n          "StudyDate": "20250107",\n          "Modality": "OCT",\n          "Laterality": "R",\n          "Manufacturer": "Zeiss",\n          "SeriesDescription": "Macular Cube"\n        }\n        ',
                        null=True,
                    ),
                ),
                (
                    "viewable_image",
                    models.FileField(
                        blank=True, null=True, upload_to="viewable-images/%Y/%m/%d/"
                    ),
                ),
                (
                    "series_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Groups related photos together",
                        null=True,
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("before", "Before"),
                            ("during", "During"),
                            ("after", "After"),
                            ("baseline", "Baseline"),
                            ("follow_up", "Follow-up"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "time_point",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Pre-op', '1 week', '1 month', '3 months'",
                        max_length=100,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        help_text="Drawing data for image markup (arrows, circles, measurements)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Tags for organization and search"
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(
                        blank=True,
                        help_text="Extracted text from document (searchable)",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Requires additional permissions to view",
                    ),
                ),
                (
                    "shared_with_patient",
                    models.BooleanField(
                        default=False, help_text="Visible in patient portal"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.clinic",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clinical_images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("measurement", "Measurement"),
                            ("arrow", "Arrow"),
                            ("circle", "Circle"),
                            ("text", "Text Label"),
                            ("highlight", "Highlight"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text='\n        {\n          "type": "measurement",\n          "coordinates": [[x1, y1], [x2, y2]],\n          "value": "12.3mm",\n          "color": "#FF0000"\n        }\n        '
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_annotations",
                        to="images.clinicalimage",
                    ),
                ),
            ],
            options={
                "db_table": "image_annotations",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "series_type",
                    models.CharField(
                        choices=[
                            ("before_after", "Before/After"),
                            ("progress", "Progress Photos"),
                            ("multi_view", "Multi-view"),
                            ("comparison", "Comparison"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_series",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Image series",
                "db_table": "image_series",
            },
        ),
        migrations.AddIndex(
            model_name="clinicalimage",
            index=models.Index(
                fields=["patient", "-uploaded_at"],
                name="clinical_im_patient_fe6e17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalimage",
            index=models.Index(
                fields=["encounter"], name="clinical_im_encount_f69353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalimage",
            index=models.Index(
                fields=["series_id"], name="clinical_im_series__4b5686_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalimage",
            index=models.Index(
                fields=["image_type", "specialty"],
                name="clinical_im_image_t_0f90b1_idx",
            ),
        ),
    ]
