# Generated by Django 5.0.1 on 2026-01-09 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("patients", "0002_patient_ethnicity_patient_gender_identity_and_more"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["scheduled_start"]},
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="scheduling__clinic__5634d8_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="scheduling__status_1008cc_idx",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="scheduled_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="scheduled_start",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["clinic", "scheduled_start"],
                name="scheduling__clinic__465355_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["clinic", "status", "scheduled_start"],
                name="scheduling__clinic__f87512_idx",
            ),
        ),
    ]
