# Generated by Django 5.0.1 on 2026-01-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("checked_in", "Checked In"),
                    ("roomed", "Roomed"),
                    ("ready", "Ready"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="checked_in",
                max_length=20,
            ),
        ),
    ]
