# Generated by Django 5.0.1 on 2026-01-10 03:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("patients", "0002_patient_ethnicity_patient_gender_identity_and_more"),
        ("scheduling", "0003_patientcheckin_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcheckin",
            name="status_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("checked_in", "Checked In"),
                    ("roomed", "Roomed"),
                    ("ready", "Ready"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                db_index=True,
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="patientcheckin",
            index=models.Index(
                fields=["clinic", "status", "check_in_time"],
                name="scheduling__clinic__8392fa_idx",
            ),
        ),
    ]
