# Generated by Django 5.0.1 on 2026-01-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_patientcheckin_status_changed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcheckin",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkins",
                to="scheduling.appointment",
            ),
        ),
    ]
