# Generated by Django 5.0.1 on 2026-01-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_patientcheckin_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcheckin",
            name="assigned_staff_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="patientcheckin",
            name="provider_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="patientcheckin",
            name="room",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
