# Generated by Django 5.0.1 on 2026-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_patientcheckin_assigned_staff_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcheckin",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientcheckin",
            name="in_progress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientcheckin",
            name="ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientcheckin",
            name="roomed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
