# Generated by Django 5.0.1 on 2026-01-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
        ("scheduling", "0008_checkinstatusevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="providers.provider",
            ),
        ),
    ]
