# Generated by Django 5.0.1 on 2026-01-16 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("scheduling", "0013_pacuadditionalnursingnotes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PacuRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surgeon", models.CharField(blank=True, default="", max_length=200)),
                (
                    "anesthesiologist",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("procedure", models.CharField(blank=True, default="", max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("airway", models.CharField(blank=True, default="", max_length=50)),
                ("airway_dc_time", models.TimeField(blank=True, null=True)),
                ("o2_lpm", models.CharField(blank=True, default="", max_length=20)),
                ("o2_device", models.CharField(blank=True, default="", max_length=50)),
                (
                    "allergies_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "anesthesia_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("asa_level", models.CharField(blank=True, default="", max_length=10)),
                ("aldrete", models.JSONField(blank=True, default=dict)),
                ("medications_rows", models.JSONField(blank=True, default=list)),
                ("patient_assessment_rows", models.JSONField(blank=True, default=list)),
                ("wound_extremity_rows", models.JSONField(blank=True, default=list)),
                ("intake", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("discharge", models.JSONField(blank=True, default=dict)),
                ("is_signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signature_data_url", models.TextField(blank=True, default="")),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "signature_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacu_record",
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacu_records",
                        to="core.clinic",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
