# Generated by Django 5.0.1 on 2026-01-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0014_pacurecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pacurecord",
            name="airway",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="airway_dc_time",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="aldrete",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="allergies_text",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="anesthesia_type",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="anesthesiologist",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="asa_level",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="date",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="discharge",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="intake",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="medications_rows",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="o2_device",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="o2_lpm",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="output",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="procedure",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="signature_hash",
        ),
        migrations.RemoveField(
            model_name="pacurecord",
            name="surgeon",
        ),
        migrations.AddField(
            model_name="pacurecord",
            name="aldrete_rows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pacurecord",
            name="general_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pacurecord",
            name="intake_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pacurecord",
            name="medication_rows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pacurecord",
            name="output_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
