# Generated by Django 5.0.1 on 2026-01-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0015_remove_pacurecord_airway_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="airway",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="airway_dc_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="allergies_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="anesthesia_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="anesthesiologist",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="arrival_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="asa_level",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="breath_sounds",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="cardiac",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="discharge_comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="discharge_other",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="discharge_pain_level",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="discharge_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="discharge_via",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="discharged_to",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="iv_dc_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="iv_site",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="iv_without_redness_swelling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="lower_extremities_motor",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="lower_extremities_sensory",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="lungs",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="neuro_orientation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="neuro_other",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="nkda",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="o2_dc_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="o2_device",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="o2_lpm",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="procedure",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="respirations_even_unlabored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="surgeon",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="upper_extremities_motor",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="upper_extremities_sensory",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pacuadditionalnursingnotes",
            name="vital_signs_stable",
            field=models.BooleanField(default=False),
        ),
    ]
