# Generated by Django 5.0.1 on 2026-01-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0017_remove_pacuadditionalnursingnotes_airway_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurgeryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure", models.CharField(max_length=255)),
                ("surgeon", models.CharField(max_length=255)),
                ("anesthesiologist", models.CharField(blank=True, max_length=255)),
                ("scheduled_date", models.DateField()),
                ("scheduled_start_time", models.TimeField()),
                ("scheduled_end_time", models.TimeField(blank=True, null=True)),
                ("room", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgery_case",
                        to="scheduling.patientcheckin",
                    ),
                ),
            ],
        ),
    ]
