# Generated by Django 5.0.1 on 2026-01-26 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("scheduling", "0018_surgerycase"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgerycase",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surgery_cases",
                to="core.clinic",
            ),
        ),
    ]
