# Generated by Django 5.0.1 on 2026-01-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0020_alter_surgerycase_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacurecord",
            name="pacu_autofilled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pacurecord",
            name="pacu_autofilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
