# Generated by Django 5.0.1 on 2026-01-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0021_pacurecord_pacu_autofilled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacurecord",
            name="pacu_autofill_locked",
            field=models.BooleanField(default=False),
        ),
    ]
