# Generated by Django 5.0.1 on 2026-01-27 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("scheduling", "0022_pacurecord_pacu_autofill_locked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmediatePostOpProgressNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surgeon_assist",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("pre_procedure_diagnosis", models.TextField(blank=True, default="")),
                ("post_procedure_diagnosis_same", models.BooleanField(default=False)),
                (
                    "post_procedure_diagnosis_other",
                    models.TextField(blank=True, default=""),
                ),
                ("anesthesia_general", models.BooleanField(default=False)),
                ("anesthesia_spinal", models.BooleanField(default=False)),
                ("anesthesia_epidural", models.BooleanField(default=False)),
                ("anesthesia_mac_local", models.BooleanField(default=False)),
                ("anesthesia_regional", models.BooleanField(default=False)),
                ("anesthesia_local", models.BooleanField(default=False)),
                ("anesthesia_iv_sedation", models.BooleanField(default=False)),
                (
                    "procedure_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("findings", models.TextField(blank=True, default="")),
                (
                    "disposition",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "disposition_other",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("status_stable", models.BooleanField(default=False)),
                (
                    "status_other",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("drain_or_pack_none", models.BooleanField(default=False)),
                ("drain_or_pack_yes", models.BooleanField(default=False)),
                (
                    "drain_or_pack_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("complications_none", models.BooleanField(default=False)),
                (
                    "complications_other",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ebl_negligible", models.BooleanField(default=False)),
                ("ebl_mls", models.CharField(blank=True, default="", max_length=50)),
                ("specimen_no", models.BooleanField(default=False)),
                ("specimen_pathology", models.BooleanField(default=False)),
                ("specimen_discarded", models.BooleanField(default=False)),
                (
                    "operative_note_dictated_required",
                    models.BooleanField(default=False),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signature_data_url", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immediate_postop_note",
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immediate_postop_notes",
                        to="core.clinic",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
