# Generated by Django 5.0.1 on 2026-01-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0023_immediatepostopprogressnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="immediatepostopprogressnote",
            name="pacu_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="immediate_postop_note",
                to="scheduling.pacurecord",
            ),
        ),
    ]
