# Generated by Django 5.0.1 on 2026-02-02 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("scheduling", "0029_anesthesiaorders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentForAnesthesiaServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nkda", models.BooleanField(default=False)),
                (
                    "allergies_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("consent", models.JSONField(blank=True, default=dict)),
                (
                    "patient_signature_data_url",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "witness_signature_data_url",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "guardian_signature_data_url",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "anesthesiologist_signature_data_url",
                    models.TextField(blank=True, default=""),
                ),
                ("is_signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anesthesia_consent",
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anesthesia_consents",
                        to="core.clinic",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
