# Generated by Django 5.0.1 on 2026-02-03 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("scheduling", "0031_historyandphysical"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeSurgeryCommunicationChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page1", models.JSONField(blank=True, default=dict)),
                (
                    "preop_signature_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "preop_signature_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "before_induction_signature_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "before_induction_signature_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "before_incision_signature_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "before_incision_signature_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "before_leaving_room_signature_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "before_leaving_room_signature_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safe_surgery_checklists",
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safe_surgery_checklists",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_safe_surgery_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_safe_surgery_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
