# Generated by Django 5.0.1 on 2026-02-03 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("scheduling", "0032_safesurgerycommunicationchecklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="FallRiskAssessmentPreOp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("total_score", models.IntegerField(default=0)),
                ("nurse_signature", models.JSONField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FallRiskAssessmentPreOpTesting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("total_score", models.IntegerField(default=0)),
                ("nurse_signature", models.JSONField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicationReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("rn_signature", models.JSONField(blank=True, null=True)),
                ("surgeon_signature", models.JSONField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientEducationDVTPE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_signature", models.JSONField()),
                ("nurse_signature", models.JSONField()),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientEducationInfectionRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_signature", models.JSONField()),
                ("nurse_signature", models.JSONField()),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientInstructions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("call_attempts", models.JSONField(blank=True, default=list)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostOpPhoneCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_attempts", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreoperativeNursesNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("nurse_signature", models.JSONField(blank=True, null=True)),
                ("patient_signature", models.JSONField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreOpPhoneCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_attempts", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.patientcheckin",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.clinic"
                    ),
                ),
            ],
        ),
    ]
