# Generated by Django 5.0.1 on 2026-02-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0034_fallriskassessmentpreop_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patienteducationdvtpe",
            name="nurse_signature",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="patienteducationdvtpe",
            name="patient_signature",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="patienteducationinfectionrisk",
            name="nurse_signature",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="patienteducationinfectionrisk",
            name="patient_signature",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
