# Generated by Django 5.0.1 on 2026-03-03 18:58

import json
from django.db import migrations, models


FIELDS = ["history", "ros", "meds", "pe", "plan", "notes"]


def parse_textfields_to_json(apps, schema_editor):
    AnesthesiaRecord = apps.get_model("scheduling", "AnesthesiaRecord")
    for record in AnesthesiaRecord.objects.all():
        changed = False
        for field in FIELDS:
            val = getattr(record, field)
            if isinstance(val, str):
                val = val.strip()
                if not val:
                    setattr(record, field, {})
                    changed = True
                else:
                    try:
                        parsed = json.loads(val)
                        setattr(record, field, parsed if isinstance(parsed, dict) else {})
                        changed = True
                    except (json.JSONDecodeError, ValueError):
                        # Not valid JSON — store as {"raw": original_value} to preserve data
                        setattr(record, field, {"raw": val})
                        changed = True
        if changed:
            record.save(update_fields=FIELDS)


def reverse_json_to_text(apps, schema_editor):
    AnesthesiaRecord = apps.get_model("scheduling", "AnesthesiaRecord")
    for record in AnesthesiaRecord.objects.all():
        for field in FIELDS:
            val = getattr(record, field)
            if isinstance(val, dict):
                setattr(record, field, json.dumps(val))
        record.save(update_fields=FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0036_remove_fallriskassessmentpreop_data_and_more"),
    ]

    operations = [
        # Step 1: parse any stringified JSON into real dicts before type change
        migrations.RunPython(
            parse_textfields_to_json,
            reverse_code=reverse_json_to_text,
        ),

        # Step 2: alter column types
        migrations.AlterField(
            model_name="anesthesiarecord",
            name="history",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="anesthesiarecord",
            name="meds",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="anesthesiarecord",
            name="notes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="anesthesiarecord",
            name="pe",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="anesthesiarecord",
            name="plan",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="anesthesiarecord",
            name="ros",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
