# Generated by Django 5.0.1 on 2026-03-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0037_convert_anesthesia_record_textfields_to_jsonfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientcheckin",
            old_name="completed_at",
            new_name="discharged_at",
        ),
        migrations.RenameField(
            model_name="patientcheckin",
            old_name="in_progress_at",
            new_name="operating_room_at",
        ),
        migrations.RenameField(
            model_name="patientcheckin",
            old_name="ready_at",
            new_name="pacu_at",
        ),
        migrations.RenameField(
            model_name="patientcheckin",
            old_name="roomed_at",
            new_name="pre_op_at",
        ),
        migrations.AlterField(
            model_name="patientcheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("checked_in", "Checked In"),
                    ("pre_op", "Pre-Op"),
                    ("operating_room", "Operating Room"),
                    ("pacu", "PACU"),
                    ("discharged", "Discharged"),
                ],
                db_index=True,
                default="checked_in",
                max_length=20,
            ),
        ),
    ]
