# Generated by Django 5.0.1 on 2026-03-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0038_asc_patient_status_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("checked_in", "Checked In"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                db_index=True,
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
