# Generated by Django 5.0.1 on 2026-01-07 21:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("usage_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Diagnoses",
                "db_table": "diagnoses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("specialty", models.CharField(blank=True, max_length=50)),
                (
                    "default_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "procedures",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encounter_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("new_patient", "New Patient"),
                            ("established", "Established Patient"),
                            ("follow_up", "Follow-up"),
                            ("annual_physical", "Annual Physical"),
                            ("pre_op", "Pre-operative"),
                            ("post_op", "Post-operative"),
                            ("consultation", "Consultation"),
                            ("procedure", "Procedure"),
                            ("surgery", "Surgery"),
                            ("emergency", "Emergency"),
                            ("telemedicine", "Telemedicine"),
                        ],
                        max_length=30,
                    ),
                ),
                ("chief_complaint", models.TextField()),
                ("specialty", models.CharField(blank=True, max_length=50)),
                (
                    "clinical_data",
                    models.JSONField(
                        default=dict, help_text="Specialty-specific exam data"
                    ),
                ),
                ("assessment", models.TextField(blank=True)),
                ("plan", models.TextField(blank=True)),
                (
                    "billing_codes",
                    models.JSONField(default=list, help_text="CPT codes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("pending_signature", "Pending Signature"),
                            ("signed", "Signed"),
                            ("amended", "Amended"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("is_amended", models.BooleanField(default=False)),
                ("amendment_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("imported_from_imed", models.BooleanField(default=False)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnoses",
                    models.ManyToManyField(blank=True, to="encounters.diagnosis"),
                ),
                (
                    "original_encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_as_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedures",
                    models.ManyToManyField(blank=True, to="encounters.procedure"),
                ),
            ],
            options={
                "db_table": "encounters",
                "ordering": ["-encounter_date"],
            },
        ),
        migrations.CreateModel(
            name="ElectronicSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signer_name", models.CharField(max_length=200)),
                ("signer_credentials", models.CharField(blank=True, max_length=100)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meaning",
                    models.CharField(
                        choices=[
                            ("authorship", "Authorship"),
                            ("review", "Review"),
                            ("approval", "Approval"),
                            ("co_signature", "Co-signature"),
                        ],
                        default="authorship",
                        max_length=20,
                    ),
                ),
                ("password_verified", models.BooleanField(default=False)),
                ("biometric_verified", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 hash of signed content", max_length=64
                    ),
                ),
                (
                    "signature_hash",
                    models.CharField(
                        help_text="Hash of signature components for verification",
                        max_length=64,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="encounters.encounter",
                    ),
                ),
            ],
            options={
                "db_table": "electronic_signatures",
                "ordering": ["-signed_at"],
                "permissions": [
                    ("view_electronic_signature", "Can view electronic signatures")
                ],
            },
        ),
        migrations.CreateModel(
            name="Vital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "temperature_unit",
                    models.CharField(
                        choices=[("F", "Fahrenheit"), ("C", "Celsius")],
                        default="F",
                        max_length=1,
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, help_text="BPM", null=True),
                ),
                ("blood_pressure_systolic", models.IntegerField(blank=True, null=True)),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, help_text="Breaths per minute", null=True
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.IntegerField(blank=True, help_text="SpO2 %", null=True),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Inches",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pounds",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "pain_level",
                    models.IntegerField(blank=True, help_text="0-10 scale", null=True),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vitals",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["patient", "-encounter_date"],
                name="encounters_patient_76b8cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["provider", "-encounter_date"],
                name="encounters_provide_730dc8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["clinic", "-encounter_date"],
                name="encounters_clinic__af0518_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(fields=["status"], name="encounters_status_2bbb51_idx"),
        ),
    ]
