# Generated by Django 5.0.1 on 2026-01-13 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_clinic_workflow_labels"),
        ("patients", "0002_patient_ethnicity_patient_gender_identity_and_more"),
        ("scheduling", "0009_appointment_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("consent", "Consent"),
                            ("h_p", "H&P"),
                            ("op_note", "Operative Note"),
                            ("anesthesia", "Anesthesia Record"),
                            ("implant", "Implant / Sticker"),
                            ("referral", "Referral"),
                            ("insurance", "Insurance Card"),
                            ("image", "Image"),
                            ("form", "Form"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.BigIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "patient", "uploaded_at"],
                        name="documents_d_clinic__d2606b_idx",
                    ),
                    models.Index(
                        fields=["clinic", "appointment", "uploaded_at"],
                        name="documents_d_clinic__ff9243_idx",
                    ),
                    models.Index(
                        fields=["clinic", "doc_type", "uploaded_at"],
                        name="documents_d_clinic__9fe1f5_idx",
                    ),
                ],
            },
        ),
    ]
