# Generated by Django 5.0.1 on 2026-01-07 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("encounters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPopulationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("last_value", "Use last recorded value"),
                            ("carry_forward", "Carry forward if unchanged"),
                            ("carry_forward_active", "Carry forward only active items"),
                            ("conditional", "Conditional based on other fields"),
                            ("calculated", "Calculate from other fields"),
                            ("default", "Use default value"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Configuration for the rule:\n        {\n          "source": "last_encounter.clinical_data.lens_od",\n          "condition": "diagnosis != \'cataract\'",\n          "default": "clear"\n        }\n        ',
                    ),
                ),
                ("specialty", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "auto_population_rules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FieldType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "config_schema",
                    models.JSONField(
                        default=dict, help_text="JSON schema for field configuration"
                    ),
                ),
                ("supports_validation", models.BooleanField(default=True)),
                ("supports_auto_population", models.BooleanField(default=True)),
                ("supports_conditional_display", models.BooleanField(default=True)),
                ("example_config", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "field_types",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="LayoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("ophthalmology", "Ophthalmology"),
                            ("orthopedics", "Orthopedics"),
                            ("cosmetic", "Cosmetic Surgery"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("new_patient", "New Patient"),
                            ("follow_up", "Follow-up"),
                            ("annual_physical", "Annual Physical"),
                            ("pre_op", "Pre-operative"),
                            ("post_op", "Post-operative"),
                            ("consultation", "Consultation"),
                            ("procedure", "Procedure"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="If true, all clinics can use this template",
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Structure:\n        {\n          "pages": [\n            {\n              "page_number": 1,\n              "sections": [\n                {\n                  "id": "demographics",\n                  "title": "Patient Information",\n                  "position": {"x": 0, "y": 0, "width": 12, "height": 2},\n                  "fields": [\n                    {\n                      "name": "patient_name",\n                      "label": "Patient Name",\n                      "type": "text",\n                      "required": true,\n                      "auto_populate": "patient.full_name",\n                      "readonly": true\n                    }\n                  ]\n                }\n              ]\n            }\n          ],\n          "auto_population_rules": {\n            "allergies": "carry_forward",\n            "medications": "carry_forward_active_only"\n          }\n        }\n        ',
                    ),
                ),
                ("auto_population_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, only this clinic can use this template",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_templates",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_layout_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="layouts.layouttemplate",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, only this provider can use this template",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "layout_templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LayoutUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_to_complete_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "user_rating",
                    models.IntegerField(blank=True, help_text="1-5 stars", null=True),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_usage",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="layouts.layouttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "layout_usage_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LayoutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("specialty", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exam", "Examination"),
                            ("history", "History"),
                            ("assessment", "Assessment"),
                            ("plan", "Plan"),
                            ("procedures", "Procedures"),
                            ("vitals", "Vital Signs"),
                            ("images", "Images"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=list,
                        help_text='\n        List of fields in this section:\n        [\n          {\n            "name": "va_od",\n            "label": "Visual Acuity OD",\n            "type": "select",\n            "options": ["20/20", "20/25", "20/30", ...],\n            "required": false,\n            "auto_populate": "last_value",\n            "validation": {"pattern": "^\\d+/\\d+$"}\n          }\n        ]\n        ',
                    ),
                ),
                ("default_width", models.IntegerField(default=6)),
                ("default_height", models.IntegerField(default=4)),
                ("default_auto_population", models.JSONField(default=dict)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="If true, all users can see and use this section",
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "layout_sections",
                "ordering": ["specialty", "category", "name"],
                "indexes": [
                    models.Index(
                        fields=["specialty", "category"],
                        name="layout_sect_special_4b4c33_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="layouttemplate",
            index=models.Index(
                fields=["specialty", "visit_type"],
                name="layout_temp_special_76a9b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="layouttemplate",
            index=models.Index(
                fields=["clinic", "specialty"], name="layout_temp_clinic__a6d0ac_idx"
            ),
        ),
    ]
