# Generated by Django 5.0.1 on 2026-01-07 21:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("user_role", models.CharField(max_length=30)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("read", "Viewed"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("print", "Printed"),
                            ("export", "Exported"),
                            ("email", "Emailed"),
                            ("login", "Logged in"),
                            ("logout", "Logged out"),
                            ("failed_login", "Failed login attempt"),
                            ("password_change", "Changed password"),
                            ("password_reset", "Reset password"),
                            ("mfa_enable", "Enabled MFA"),
                            ("mfa_disable", "Disabled MFA"),
                            ("signature", "Electronically signed"),
                            ("break_glass", "Emergency access (Break the Glass)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.IntegerField(null=True)),
                ("resource_repr", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for access (e.g., 'Emergency access')",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="{'field_name': {'old': 'value', 'new': 'value'}}",
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("previous_log_hash", models.CharField(blank=True, max_length=64)),
                ("log_hash", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "permissions": [("view_audit_log", "Can view audit logs")],
            },
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "texas_medical_board_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "npi",
                    models.CharField(
                        blank=True,
                        help_text="National Provider Identifier",
                        max_length=10,
                    ),
                ),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(default="TX", max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "clinic_type",
                    models.CharField(
                        choices=[
                            ("primary_care", "Primary Care"),
                            ("specialty", "Specialty Practice"),
                            ("surgery_center", "Surgery Center"),
                            ("multi_specialty", "Multi-Specialty Practice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specialties",
                    models.JSONField(default=list, help_text="List of specialties"),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Chicago", max_length=50),
                ),
                ("hipaa_trained", models.BooleanField(default=False)),
                (
                    "baa_signed_date",
                    models.DateField(
                        blank=True, help_text="Business Associate Agreement", null=True
                    ),
                ),
                ("last_security_audit", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clinics",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_configuration",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("physician", "Physician"),
                            ("surgeon", "Surgeon"),
                            ("nurse_practitioner", "Nurse Practitioner"),
                            ("physician_assistant", "Physician Assistant"),
                            ("nurse", "Nurse"),
                            ("tech", "Technician"),
                            ("scribe", "Scribe"),
                            ("front_desk", "Front Desk"),
                            ("surgery_scheduler", "Surgery Scheduler"),
                            ("or_nurse", "OR Nurse"),
                            ("anesthesiologist", "Anesthesiologist"),
                            ("admin", "Administrator"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "npi",
                    models.CharField(
                        blank=True,
                        help_text="National Provider Identifier",
                        max_length=10,
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=50)),
                (
                    "license_state",
                    models.CharField(blank=True, default="TX", max_length=2),
                ),
                (
                    "dea_number",
                    models.CharField(
                        blank=True, help_text="DEA for prescribing", max_length=20
                    ),
                ),
                ("specialties", models.JSONField(default=list)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("default_encounter_type", models.CharField(blank=True, max_length=50)),
                ("auto_population_enabled", models.BooleanField(default=True)),
                ("hipaa_trained", models.BooleanField(default=False)),
                ("hipaa_training_date", models.DateField(blank=True, null=True)),
                ("hipaa_training_expires", models.DateField(blank=True, null=True)),
                ("last_password_change", models.DateTimeField(blank=True, null=True)),
                ("password_expires_at", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["last_name", "first_name"],
                "permissions": [
                    ("view_phi", "Can view Protected Health Information"),
                    ("export_data", "Can export patient data"),
                    ("break_the_glass", "Can access restricted patient records"),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
