# Generated by Django 5.0.1 on 2026-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="timezone",
            field=models.CharField(default="America/Chicago", max_length=64),
        ),
    ]
