# Generated by Django 5.0.1 on 2026-01-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_clinic_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="workflow_labels",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
